apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ec2off-manager-role
rules:
- apiGroups:
  - ec2.ec2offering.crossplane.io
  resources:
  - instancetypeofferings
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ec2.ec2offering.crossplane.io
  resources:
  - instancetypeofferings/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ec2.ec2offering.crossplane.io
  resources:
  - instancetypeofferings/finalizers
  verbs:
  - update
- apiGroups:
  - ec2.ec2offering.crossplane.io
  resources:
  - spotadvisordatas
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ec2.ec2offering.crossplane.io
  resources:
  - spotadvisordatas/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ec2.ec2offering.crossplane.io
  resources:
  - spotadvisordatas/finalizers
  verbs:
  - update
- apiGroups:
  - ec2offering.crossplane.io
  resources:
  - providerconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ec2offering.crossplane.io
  resources:
  - providerconfigs/status
  verbs:
  - get
- apiGroups:
  - ec2offering.crossplane.io
  resources:
  - providerconfigusages
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ec2offering.crossplane.io
  resources:
  - storeconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
