//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceTypeOffering) DeepCopyInto(out *InstanceTypeOffering) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceTypeOffering.
func (in *InstanceTypeOffering) DeepCopy() *InstanceTypeOffering {
	if in == nil {
		return nil
	}
	out := new(InstanceTypeOffering)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InstanceTypeOffering) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceTypeOfferingInfo) DeepCopyInto(out *InstanceTypeOfferingInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceTypeOfferingInfo.
func (in *InstanceTypeOfferingInfo) DeepCopy() *InstanceTypeOfferingInfo {
	if in == nil {
		return nil
	}
	out := new(InstanceTypeOfferingInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceTypeOfferingList) DeepCopyInto(out *InstanceTypeOfferingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InstanceTypeOffering, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceTypeOfferingList.
func (in *InstanceTypeOfferingList) DeepCopy() *InstanceTypeOfferingList {
	if in == nil {
		return nil
	}
	out := new(InstanceTypeOfferingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InstanceTypeOfferingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceTypeOfferingObservation) DeepCopyInto(out *InstanceTypeOfferingObservation) {
	*out = *in
	if in.InstanceTypeOfferings != nil {
		in, out := &in.InstanceTypeOfferings, &out.InstanceTypeOfferings
		*out = make([]InstanceTypeOfferingInfo, len(*in))
		copy(*out, *in)
	}
	if in.NextToken != nil {
		in, out := &in.NextToken, &out.NextToken
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceTypeOfferingObservation.
func (in *InstanceTypeOfferingObservation) DeepCopy() *InstanceTypeOfferingObservation {
	if in == nil {
		return nil
	}
	out := new(InstanceTypeOfferingObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceTypeOfferingParameters) DeepCopyInto(out *InstanceTypeOfferingParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceTypeOfferingParameters.
func (in *InstanceTypeOfferingParameters) DeepCopy() *InstanceTypeOfferingParameters {
	if in == nil {
		return nil
	}
	out := new(InstanceTypeOfferingParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceTypeOfferingSpec) DeepCopyInto(out *InstanceTypeOfferingSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	out.ForProvider = in.ForProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceTypeOfferingSpec.
func (in *InstanceTypeOfferingSpec) DeepCopy() *InstanceTypeOfferingSpec {
	if in == nil {
		return nil
	}
	out := new(InstanceTypeOfferingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceTypeOfferingStatus) DeepCopyInto(out *InstanceTypeOfferingStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceTypeOfferingStatus.
func (in *InstanceTypeOfferingStatus) DeepCopy() *InstanceTypeOfferingStatus {
	if in == nil {
		return nil
	}
	out := new(InstanceTypeOfferingStatus)
	in.DeepCopyInto(out)
	return out
}
